all:
	$(info After this, please run 'use "loader.sml";' in sml)
	@ml-lex pl0.lex 
	@ml-yacc pl0.yacc 
clean:
	rm pl0+rationals.lex.sml
	rm pl0+rationals.yacc.desc
	rm pl0+rationals.yacc.sig
	rm pl0+rationals.yacc.sml